ALTER TABLE EVENT_HISTORY
    MODIFY CREATE_USER VARCHAR2(100);

ALTER TABLE EVENT_HISTORY
    MODIFY UPDATE_USER VARCHAR2(100);

ALTER TABLE TRAX_UPDATED_PUB_EVENT
    MODIFY CREATE_USER VARCHAR2(100);

ALTER TABLE TRAX_UPDATED_PUB_EVENT
    MODIFY UPDATE_USER VARCHAR2(100);