GRANT SELECT ON REPLICATION_EVENT TO GRAD_READONLY;
GRANT SELECT ON REPLICATION_SHEDLOCK TO GRAD_READONLY;
GRANT SELECT ON TRAX_STUDENT_NO TO GRAD_READONLY;
GRANT SELECT ON TRAX_UPDATED_PUB_EVENT TO GRAD_READONLY;
