-- API_GRAD_TRAX.TRAX_STUDENT_NO definition

CREATE TABLE "TRAX_STUDENT_NO"
(   "STUD_NO" VARCHAR2(10) NOT NULL,
    "STATUS" VARCHAR2(1),
    CONSTRAINT "TRAX_STUDENT_NO_PK" PRIMARY KEY ("STUD_NO")
        USING INDEX TABLESPACE "API_GRAD_IDX"  ENABLE
) SEGMENT CREATION IMMEDIATE
 NOCOMPRESS LOGGING TABLESPACE "API_GRAD_DATA"   NO INMEMORY;




