-- API_GRAD_TRAX.REPLICATION_EVENT definition

CREATE TABLE "REPLICATION_EVENT"
   (	"REPLICATION_EVENT_ID" RAW(16) NOT NULL ENABLE,
	"EVENT_ID" RAW(16) NOT NULL ENABLE,
	"EVENT_PAYLOAD" BLOB NOT NULL ENABLE,
	"EVENT_STATUS" VARCHAR2(50) NOT NULL ENABLE,
	"EVENT_TYPE" VARCHAR2(100) NOT NULL ENABLE,
	"EVENT_OUTCOME" VARCHAR2(100) NOT NULL ENABLE,
	"CREATE_USER" VARCHAR2(32),
	"CREATE_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
	"UPDATE_USER" VARCHAR2(32),
	"UPDATE_DATE" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP,
	 CONSTRAINT "REPLICATION_EVENT_PK" PRIMARY KEY ("REPLICATION_EVENT_ID")
  USING INDEX TABLESPACE "API_GRAD_IDX"  ENABLE,
	 CONSTRAINT "REPLEVT_EVENT_ID_UK" UNIQUE ("EVENT_ID")
  USING INDEX TABLESPACE "API_GRAD_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
 NOCOMPRESS LOGGING
  TABLESPACE "API_GRAD_DATA"   NO INMEMORY
 LOB ("EVENT_PAYLOAD") STORE AS SECUREFILE (
  TABLESPACE "API_GRAD_BLOB_DATA" ENABLE STORAGE IN ROW CHUNK 8192) ;

CREATE INDEX "REPLEVT_EVENT_STATUS_IDX" ON "REPLICATION_EVENT" ("EVENT_STATUS")
  TABLESPACE "API_GRAD_IDX" ;

CREATE INDEX "REPLEVT_EVENT_TYPE_IDX" ON "REPLICATION_EVENT" ("EVENT_TYPE")
  TABLESPACE "API_GRAD_IDX" ;

COMMENT ON TABLE REPLICATION_EVENT IS 'This table is used to store all the received choreographed events from different api via pub/sub model and process them.';

-- API_GRAD_TRAX.REPLICATION_SHEDLOCK definition

CREATE TABLE "REPLICATION_SHEDLOCK"
   (	"NAME" VARCHAR2(64),
	"LOCK_UNTIL" TIMESTAMP (3),
	"LOCKED_AT" TIMESTAMP (3),
	"LOCKED_BY" VARCHAR2(255),
	 CONSTRAINT "REPLICATION_SHEDLOCK_PK" PRIMARY KEY ("NAME")
  USING INDEX TABLESPACE "API_GRAD_IDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE
 NOCOMPRESS LOGGING
  TABLESPACE "API_GRAD_DATA"   NO INMEMORY ;

COMMENT ON TABLE REPLICATION_SHEDLOCK IS 'This table is used to achieve distributed lock between pods, for schedulers.';

