package ca.bc.gov.educ.api.trax.util;

public interface PermissionsConstants {
	String _PREFIX = "hasAuthority('";
	String _SUFFIX = "')";

	String READ_GRAD_COUNTRY = _PREFIX + "SCOPE_READ_GRAD_COUNTRY_CODE_DATA" + _SUFFIX;
	String READ_GRAD_PROVINCE = _PREFIX + "SCOPE_READ_GRAD_PROVINCE_CODE_DATA" + _SUFFIX;
	String READ_SCHOOL_DATA = _PREFIX + "SCOPE_READ_GRAD_SCHOOL_DATA" + _SUFFIX;
	String READ_PSI_INFO = _PREFIX + "SCOPE_READ_GRAD_PSI_DATA" + _SUFFIX;

	String READ_GRAD_TRAX_STUDENT_DATA = _PREFIX + "SCOPE_READ_GRAD_TRAX_STUDENT_DATA" + _SUFFIX;
	String UPDATE_GRAD_TRAX_STUDENT_DATA = _PREFIX + "SCOPE_UPDATE_GRAD_TRAX_STUDENT_DATA" + _SUFFIX;
	String READ_GRAD_TRAX_COURSE_DATA = _PREFIX + "SCOPE_READ_GRAD_TRAX_COURSE_DATA" + _SUFFIX;
}